"""init schema

Revision ID: bf1c0d81c374
Revises: 
Create Date: 2025-11-10 23:20:11.291547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1c0d81c374'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('pdf', 'image', name='artifactkind'), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_kind'), 'artifacts', ['kind'], unique=False)
    op.create_index(op.f('ix_artifacts_sha256'), 'artifacts', ['sha256'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('config_yaml', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=True)
    op.create_table('rubrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('rubric_json', sa.JSON(), nullable=False),
    sa.Column('compiled_from_docs', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubrics_project_id'), 'rubrics', ['project_id'], unique=False)
    op.create_table('bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('vector_text', sa.Boolean(), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=False),
    sa.Column('ocr_conf', sa.Float(), nullable=False),
    sa.Column('file_sha256', sa.String(length=80), nullable=False),
    sa.Column('extracted_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bundle_project_created', 'bundles', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bundles_file_sha256'), 'bundles', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_bundles_project_id'), 'bundles', ['project_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('rubric_id', sa.Integer(), nullable=False),
    sa.Column('review_json', sa.JSON(), nullable=False),
    sa.Column('weighted_total', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_project_id'), 'reviews', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_project_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_bundles_project_id'), table_name='bundles')
    op.drop_index(op.f('ix_bundles_file_sha256'), table_name='bundles')
    op.drop_index('ix_bundle_project_created', table_name='bundles')
    op.drop_table('bundles')
    op.drop_index(op.f('ix_rubrics_project_id'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_artifacts_sha256'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_kind'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
